name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        package:
          - cli
          - core
          - matchers
          - parser
          - rebuild-matchers
          - utils

    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: packages/${{ matrix.package }}
        run: pnpm build

      - name: Run Linter
        working-directory: packages/${{ matrix.package }}
        run: pnpm lint

      - name: Run Tests
        working-directory: packages/${{ matrix.package }}
        run: pnpm test
